### ISSUE TITLE
A minor issue - looks like one of the resources is not available

### ISSUE THREAD

**Issue by gj1118** [arxeiss/Sublime-GitBadgesLikeVSCode#1]
Hi, 
First things first, thanks for this plugin. Awesome Job. That said, I am seeing the following issue 

![image](https://user-images.githubusercontent.com/473101/61558801-0d52d900-aa36-11e9-9ede-b2a63775eec3.png)

This started happening after installing this package. Can you please look into this ? 

I am seeing this errors in the console. 
```
Unable to decode Packages/ArxeissTheme/textures/added.png
Unable to decode Packages/ArxeissTheme/textures/untracked.png
Unable to decode Packages/ArxeissTheme/textures/staged.png
Unable to decode Packages/ArxeissTheme/textures/modified.png
```

Thanks

**Comment by arxeiss** [comment]
Hello, I'm really sorry, I did not get any notification about something in my own repo :/
But I found it as well, I will try to fix it ASAP

**Comment by arxeiss** [comment]
@gj1118 thank you for reporting, I'm apologised for late reply. I found, that all GitHub repos where unwatched, so I did not get any notification you submitted and issue here.

Problem is now fixed, new version released, just waiting when PackageControll will do next check (once in an hour probably) and then fixed version should arrive. I will watch it as well
