### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Ali-Aref** [arxeiss/Sublime-GitBadgesLikeVSCode#3]
Just installed **Git badges like VS Code** plugin in my Sublime Text(3.2.2) noting changed. :|

**Comment by Ali-Aref** [comment]
omg! just changed the theme :100:  and it's working.. i wish i could use it on **ayu** themes too.

**Comment by arxeiss** [comment]
Actually, you can use it with Ayu as well. There is difference between **Select color scheme** and **Select Theme**.

So do the following:

1. Open command pallete (CTRL+Shift + P) and type **UI: Select Theme** and select Adaptive od Default. (**not** Ayu)
2. Open command pallete (CTRL+Shift + P) and type **UI: Select Select Color scheme** and select any of Ayu.

**Comment by endingman** [comment]
How can I use when theme is not Adaptive?

**Comment by arxeiss** [comment]
The only supported theme is Adaptive or Default, as those are default ones from Sublime.
I see Sublime now supports also Default Dark, which I will add. But it works with Default dark already.
